title: Tutorial su EDICO
lang: it
description: EDICO - l'Editor Scientifico per persone ipovedenti e non vedenti. Potente, Facile, Gratuito.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
