url: https://www.edicoitalia.it
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


baseurl: /

# Site Settings
title: EDICO Targato Italia
description: "EDICO - l'Editor Scientifico per persone ipovedenti e non vedenti. Potente, Facile, Gratuito.\nProvalo subito!"
keywords: "edico, matematica, scienze, ipovedenti, ciechi, ausili"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["tutorial","Rakefile", "LICENSE", "readme.markdown"]
