url: http://edicoitalia.github.io
#plugins:
#  - jekyll-sitemap

baseurl: /

# Site Settings
title: EDICO Italia
description: "EDICO - l'Editor Scientifico per persone ipovedenti e non vedenti. Potente, Facile, Gratuito.\nProvalo subito!"
keywords: "edico, matematica, scienze, ipovedenti, ciechi, ausili"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["tutorial","Rakefile", "LICENSE", "readme.markdown"]
